export default {
  help: 'shows all commands',
  info: 'shows the current number and target number',
  inventory: 'shows your inventory',
  user: 'shows your statistics',
  shop: 'shows items in the shop',
  balance: 'shows your crown and coin balance',
  convert: 'converts 1 crown to 100 coins',
  'convert <n>': 'converts n crowns to coins',
  'convert all': 'converts all crowns to coins',
  'equip <reactionId>': 'equip reaction',
  'buy <item> [n]': 'buys item from the shop',
  boss: 'shows information on current boss',
  leaderboard: 'show leaderboard',
};
