export default {
  REACT_CORRECT: '✅',
  REACT_INCORRECT: '❌',
  REACT_TIMEOUT: '⏳',
  WIN: 101,
  CONVERSION_RATE: 100,
  COIN_RATE: 0.05,
  COIN_LOSS: 2,
  COIN_GAIN: 9,
  TP_MIN: 40,
  TP_MAX: 100,
  CROWN_MULTIPLIER: 1,
  BOSS_SPAWN_RATE: 0.5,
};
