export default {
  REACT_CORRECT: '✅',
  REACT_INCORRECT: '❌',
  REACT_TIMEOUT: '⏳',
  WIN: 101,
  CONVERSION_RATE: 100,
  COIN_RATE: 0.05,
  COIN_LOSS: 5,
  COIN_GAIN: 3,
  TP_MIN: 5,
  TP_MAX: 50,
  CROWN_MULTIPLIER: 3,
  BOSS_SPAWN_RATE: 0.025,
};
