module.exports = {
  REACT_CORRECT: '✅',
  REACT_INCORRECT: '❌',
  REACT_TIMEOUT: '⏳',
  WIN: 128,
  CONVERSION_RATE: 100,
  COIN_RATE: 0.01,
  COIN_LOSS: 5,
  COIN_GAIN: 10,
  TP_MIN: 10,
  TP_MAX: 60,
};
